// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messagedef.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Msg {

  /// <summary>Holder for reflection information generated from messagedef.proto</summary>
  public static partial class MessagedefReflection {

    #region Descriptor
    /// <summary>File descriptor for messagedef.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagedefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBtZXNzYWdlZGVmLnByb3RvEgNtc2cqIgoKcHJvdG9Nc2dJZBIUChBDU19M",
            "b2dpbl9SZXF1ZXN0EAE="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Msg.protoMsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum protoMsgId {
    [pbr::OriginalName("CS_Login_Request")] CsLoginRequest = 1,
  }

  #endregion

}

#endregion Designer generated code
